sudo: required
language: generic

cache:
  directories:
    - $HOME/.stack

before_install:
  # Setup local bin
  - mkdir -p "${HOME}/.local/bin"
  - export PATH="${HOME}/.local/bin:${PATH}"
  
  # Install Stack
  - ./travis/install-stack.sh

  # Install Z3
  - ./travis/install-z3.sh

  # Install Liquid Haskell
  - ./travis/install-liquid-haskell.sh

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack --no-terminal --skip-ghc-check test
