sudo: required
language: generic

cache:
  directories:
    - $HOME/.stack

before_install:
  # Setup local bin
  - mkdir -p "${HOME}/.local/bin"
  - export PATH="${HOME}/.local/bin:${PATH}"
  
  # Install Stack
  - ./travis/install-stack.sh

  # Install Z3
  - ./travis/install-z3.sh

  # Install Liquid Haskell
  - ./travis/install-liquid-haskell.sh

install:
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  # Currently tests can fail the first few times they’re run because they must
  # be run in topologically-sorted order but the order in which they run is
  # nondeterministic. As a workaround, we just try running the tests multiple
  # times. (This will hopefully be fixed soon.)
  - travis_retry stack --no-terminal --skip-ghc-check test
