name: lh-sequent-calc
version: 0.1.0
github: wkunkel/lh-sequent-calc

verbatim:
  # We need this because of a bug in hpack:
  # https://github.com/sol/hpack/issues/213
  cabal-version: '>= 2.0'

extra-source-files:
  - README.md
dependencies:
  - base ^>= 4.10
default-extensions:
  - NoImplicitPrelude

library:
  source-dirs: src
  dependencies:
    - HaTeX ^>= 3.18
  exposed-modules:
    - Prelude.Reflected
    - SequentCalc
    - SequentCalc.Latex

tests:
  liquid-haskell-tests:
    source-dirs: test
    main: Main.hs
    dependencies:
      - lh-sequent-calc
      - path ^>= 0.6
      - path-io ^>= 1.3
      - tasty ^>= 1.0
      - text ^>= 1.2
      - typed-process ^>= 0.2

executables:
  homework-1:
    source-dirs: examples/homework-1
    main: Main.hs
    dependencies:
      - lh-sequent-calc
      - HaTeX ^>= 3.18
